### ISSUE TITLE
Cannot read properly 'slots' of undefined

### ISSUE THREAD

**Issue by martylietz** [alexa/alexa-skills-kit-sdk-for-nodejs#189]
I am trying to get a session attribute to get a users name. but when I call it, it cannot read properly 'slots' of undefined.

Here is my log output:
START RequestId: dfee5395-a082-11e7-862e-6f05b61c62c7 Version: $LATEST
2017-09-23T17:16:03.550Z	dfee5395-a082-11e7-862e-6f05b61c62c7	Warning: Application ID is not set
2017-09-23T17:16:04.509Z	dfee5395-a082-11e7-862e-6f05b61c62c7	TypeError: Cannot read property 'slots' of undefined
at Object.RemebmberNameIntent (/var/task/index.js:27:57)
at emitNone (events.js:86:13)
at AlexaRequestEmitter.emit (events.js:185:7)
at Object.LaunchRequest (/var/task/index.js:22:10)
at emitNone (events.js:86:13)
at AlexaRequestEmitter.emit (events.js:185:7)
at AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:216:10)
at ValidateRequest.attributesHelper.get (/var/task/node_modules/alexa-sdk/lib/alexa.js:170:27)
at Response. (/var/task/node_modules/alexa-sdk/lib/DynamoAttributesHelper.js:43:25)
at Request. (/var/task/node_modules/alexa-sdk/node_modules/aws-sdk/lib/request.js:364:18)
at Request.callListeners (/var/task/node_modules/alexa-sdk/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/task/node_modules/alexa-sdk/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/alexa-sdk/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/alexa-sdk/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/alexa-sdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/alexa-sdk/node_modules/aws-sdk/lib/state_machine.js:26:10
END RequestId: dfee5395-a082-11e7-862e-6f05b61c62c7
REPORT RequestId: dfee5395-a082-11e7-862e-6f05b61c62c7	Duration: 1094.07 ms	Billed Duration: 1100 ms Memory Size: 128 MB	Max Memory Used: 46 MB
RequestId: dfee5395-a082-11e7-862e-6f05b61c62c7 Process exited before completing request

Here is the code when I am trying to ask for a name:
'RemebmberNameIntent': function ()
{
this.atttributes['name'] = this.event.request.intent.slots.name.value;
this.emit(':ask', 'Hi! Welcome to Welcoming Alarm! What is your name?');
if (event.request.intent.slots.name !== undefined)
{
this.emit(':ask', "Sorry, I didnt get that, could you please repeat your name?")
};
},

**Comment by realharry** [comment]
@martylietz Your example is a bit confusing. You should have asked the name somewhere else. (That is, `this.emit(':ask', 'Hi! Welcome to Welcoming Alarm! What is your name?');` belongs somewhere else not in "RemebmberNameIntent" handler. When the user answers the question _with the name_, this RemebmberNameIntent handler kicks in.) Since (I presume) the user hasn't said his/her name when this handler is called, you'll always have null value. 

I always check whether this.event.request.intent is null and whether this.event.request.intent.slots is null and whether this.event.request.intent.slots.SLOTNAME is null before I call ".value". These three can be null for any number of reasons. And, if any of these is null, you should understand why they are null.

**Comment by Amazon-tianrenz** [comment]
Thanks @realharry  for the explanation!
Hi @martylietz, 
Please make sure that your interaction model is defined so that ``RemebmberNameIntent`` is expecting slots in its utterances. Otherwise, the intent request may not include the ``slots`` in it. And that might be what's causing the problem here. 

Regards
