### ISSUE TITLE
Fails first time using a DynamoDB table

### ISSUE THREAD

**Issue by jacobweber** [alexa/alexa-skills-kit-sdk-for-nodejs#292]
I configured my skill to use a DynamoDB table that doesn't exist yet. The first time I made a request that saved state, it looked like it created the table, as expected:

```
2018-02-01T16:43:37.435Z	07e14c9d-076f-11e8-a4b2-e534b52c50ad	get error: {
    "message": "Requested resource not found",
    "code": "ResourceNotFoundException",
    "time": "2018-02-01T16:43:37.378Z",
    "requestId": "1234567890",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 29.622078060361112
}

2018-02-01T16:43:37.797Z	07e14c9d-076f-11e8-a4b2-e534b52c50ad	Creating table my-table-name:
{"TableDescription":{"AttributeDefinitions":[{"AttributeName":"userId","AttributeType":"S"}],"TableName":"my-table-name","KeySchema":[{"AttributeName":"userId","KeyType":"HASH"}],"TableStatus":"CREATING","CreationDateTime":"2018-02-01T16:43:37.757Z","ProvisionedThroughput":{"NumberOfDecreasesToday":0,"ReadCapacityUnits":5,"WriteCapacityUnits":5},"TableSizeBytes":0,"ItemCount":0,"TableArn":"arn:aws:dynamodb:us-east-1:1234567890:table/my-table-name"}}
```

But then the next time I made a request that saved state, I got an error response, and the following appeared in the logs:

```
2018-02-01T16:43:51.215Z	1512fbbc-076f-11e8-90a6-b90b34aeeea7	Error during DynamoDB put:ResourceNotFoundException: Requested resource not found

2018-02-01T16:43:51.215Z	1512fbbc-076f-11e8-90a6-b90b34aeeea7	Error saving state: ResourceNotFoundException: Requested resource not found
ResourceNotFoundException: Requested resource not found
    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:115:18)

2018-02-01T16:43:51.215Z	1512fbbc-076f-11e8-90a6-b90b34aeeea7	{"message":"Requested resource not found","code":"ResourceNotFoundException","time":"2018-02-01T16:43:51.215Z","requestId":"DBSI4GC4MH2A2KI3SC3A1I7AAVVV4KQNSO5AEMVJF66Q9ASUAAJG","statusCode":400,"retryable":false,"retryDelay":34.39000832233896}

2018-02-01T16:43:51.216Z	1512fbbc-076f-11e8-90a6-b90b34aeeea7	{"errorMessage":"Requested resource not found","errorType":"ResourceNotFoundException","stackTrace":["Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:48:27)","Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)","Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)","Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)","Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)","AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)","/var/task/node_modules/aws-sdk/lib/state_machine.js:26:10","Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)","Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)","Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:115:18)"]}
```

After a couple requests it started working. Maybe it wasn't waiting for the table to be available before it started writing to it?

This pattern has repeated itself several times, with different tables.

**Comment by talkingnews** [comment]
Yes, DynamoDB is horribly slow and laggy. I've known it to take 3 minutes just to create a new table.
I think AWS need to give the poor thing a bit of attention, but that said, once the table is created, it seems to write small amounts of data reasonably quickly. The trick is to just to remember that it can often take minutes just to create a table, but as long as it only needs doing once, it should be OK.
It's been laggy like this for as long as I've been messing with Alexa, which is at least 6 months.

**Comment by bobharrisuk** [comment]
Hi - I've had timeouts on the first use of a Skill when the table is being created and, occasionally, have had to up the Lambda timeout parameter from the default 3 seconds.  Not had issues with subsequent uses though.

**Comment by Amazon-tianrenz** [comment]
Hi @jacobweber, 

In v1 SDK, it tries to create the table if non is found for the first time using. Creating a DynamoDB table can take time and will cause subsequent request to fail if still in the process of creating. 

We've released ASK SDK v2 for Node.js yesterday, which aims to address many of the issues here. Now the behavior of auto create table can be switched off. We encourage you to check out our wiki [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki).

**Comment by dante-byte** [comment]
i'm having the same issue I read the documentation on amazon, but i have a simple post request, my. get request works but my post request doesn't i dont' my sharing my code I'm making. a simple crud app for a demo
