### ISSUE TITLE
serviceClientFactory was undefined

### ISSUE THREAD

**Issue by mehtanilay10** [alexa/alexa-skills-kit-sdk-for-nodejs#356]
I have read the document on Service client and tried to Address via it.
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki/Alexa-Service-Clients

```
const { requestEnvelope, serviceClientFactory } = handlerInput;
const { deviceId } = requestEnvelope.context.System.device;
const deviceAddressServiceClient = serviceClientFactory.getDeviceAddressServiceClient();
const address = deviceAddressServiceClient.getFullAddress(deviceId);
console.log('Addres: ' + address);
```

But I got serviceClientFactory was undefined in handlerInput.
As per this below condition, I have to set ApiClient value.
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/fdf4a04c853bbe38dc6aecfe16117a07c4a27948/ask-sdk-core/lib/skill/Skill.ts#L80-L86

For this, I am used withApiClient() of CustomSkillBuilder. So i am used below snippet.
```
exports.handler = skillBuilder
	.addRequestHandlers(...)
	.withSkillId(...)
	.withApiClient(new ApiClient())
	.lambda();
```

## Expected Behavior
How to solve this issue? Is there anything i missed?

## Current Behavior
Currently it generate below error:
> module initialization error: ReferenceError
> at Object.<anonymous> (/var/task/index.js:294:21)
> at Module._compile (module.js:652:30)
> at Object.Module._extensions..js (module.js:663:10)
> at Module.load (module.js:565:32)
> at tryModuleLoad (module.js:505:12)
> at Function.Module._load (module.js:497:3)
> at Module.require (module.js:596:17)
> at require (internal/module.js:11:18)

## Context
Unable to obtain address of user, due to serviceClientFactory. 

## Your Environment
* ASK SDK for Node.js used: 2.0
* Operating System and version: Windows 10 v1703

## Node.js and NPM Info
* Node.js version used for development:7.2.0
* NPM version used for development:3.10.9

**Comment by TianTXie** [comment]
Hi @mehtanilay10,  what package do you use? If you want to use default apiClient, you can use StandardSkillBuilder which is in ask-sdk package and you don't need to set anything in StandardSkillBuilder. If you want to use your own apiClient, you can use CustomSkillBuilder which is in ask-sdk-core package. In CustomSkillBuilder, there is a withApiClient() method which allows you to set your apiClient.

**Comment by mehtanilay10** [comment]
I have used v2 packages only. So what should I pass here?
I have found something like below snippet.

https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/fdf4a04c853bbe38dc6aecfe16117a07c4a27948/ask-sdk-v1adapter/lib/adapter.ts#L192-L196

**Comment by TianTXie** [comment]
@mehtanilay10  Are you using Standard ASK SDK Distribution or Core SDK Module Only in this [link](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki/Setting-Up-The-ASK-SDK).

**Comment by mehtanilay10** [comment]
I have used only **ask-sdk-core**

**Comment by TianTXie** [comment]
If you want to use default apiClient, try
```
const skillBuilder = Alexa.SkillBuilders.custom();
exports.handler = skillBuilder
	.addRequestHandlers(...)
       . withApiClient(new Alexa.DefaultApiClient())
	.withSkillId(...)
	.lambda();
```

**Comment by ghost** [comment]
can someone post code if you are using the standard skill builder for accessing the apiclient. I'm trying to get the timezone of the device.  I need to use the standard skill builder, not the custom one because i use all the helper methods for dynamodb that comes with standard.   I have yet to find an example of how to get the device time zone using standard

**Comment by franklin-lobb** [comment]
@dante2365  the code located [here](https://github.com/alexa/alexa-cookbook/blob/master/feature-demos/skill-demo-device-settings/lambda/custom/index.js) will work.  When you use `.standard()` Skill Builder instead of the `.custom()` one, you don't need to include this line `.withApiClient(new Alexa.DefaultApiClient())`.  The Standard includes it by default.

**Comment by ghost** [comment]
thank you @franklin-lobb.   That worked.  Every example I found was with the custom skill builder so when I included the .withApiClient I got the function does not exist error.

**Comment by nnnayan** [comment]
Thanks, this solution worked for me too!
