### ISSUE TITLE
got error: Caught Error: { AskSdk.DynamoDbPersistenceAdapter Error: Could not save item (amzn1.ask.account.....) to table (InternetArchiveSessions): The parameter cannot be converted to a numeric value: NaN

### ISSUE THREAD

**Issue by hyzhak** [alexa/alexa-skills-kit-sdk-for-nodejs#378]
## Update

Thanks to @tianrenz I've found that original attributes contains `NaN` values. So possible solution:

```javascript
JSON.parse(JSON.stringify(attrs))
```

## I'm submitting a...
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
I'm trying to save alexa skill state to DynamoDB session table and usually it works.
``` javascript
const persistentAttributes = {"id":"amzn1.ask.account.AESW4Y2T3NOFH6AFOZRROM46HVP7RXZWITXM4HFDY2G72UTHWQOJRWBPH26T7NHIGKF7NHYZQVAQUXCZSMHH3NL7L5CSBAFWGCZRBMDCYI5U5MB7BP2UCUWYOPD2IDAVLVOMLLFRF6LE4UPFBSNV43JLCMMS2DP3NFS7CRDH2SC5DFJETU6KSANDZ2G6CCHXEXE4CGF2CFQFHRA","attributes":{"amzn1.ask.device.AHDIDEBSPA33HUZNNIBVHB6SREOR26JVMCTUR6SQZDTTDXONVZNGU3GG2HFOABJZIRFUJUMEJTKRSKZ7YC7BKGOMQVWFNBJSS35Y2DSZUEOBNPKQPWSJTM6PJOKSBBLG667ZDKIQRH3GFA5NZXES3HP5SNNQ":{"fsm":{"state":"playback"},"dialog":{"lastPhrase":{"speech":"You've selected 78s. What genre of music would you like to listen to? Please select a topic like Jazz, Instrumental or Dance?","suggestions":["Jazz","Instrumental","Dance"],"reprompt":null}},"query":{"values":{"collectionId":"georgeblood","order":"random","subject":"dance"}},"playlist":{"feederName":"albums-async","extra":{"cursor":{"current":{"album":0,"song":0},"total":{"songs":1,"albums":1358}}},"current":0,"items":[{"filename":"02 - Blossom Time Waltzes - Sigmund Romberg and his Orchestra.mp3","title":"Blossom Time Waltzes","audioURL":"https://archive.org/download/78_blossom-time-waltzes_sigmund-romberg-and-his-orchestra-lehar_gbia0020410/02%20-%20Blossom%20Time%20Waltzes%20-%20Sigmund%20Romberg%20and%20his%20Orchestra.mp3","collections":["78rpm","78rpm_mcneil","georgeblood","audio_music"],"coverage":"USA","creator":["Sigmund Romberg and his Orchestra","Lehar","Dorothy Donnelly","Schubert","Berte","Sigmund Romberg","Ziehrar","Romberg","Oscar Hammerstein, II","Johann Strauss, Jr.","Harbach","Hammerstein II","Mandel"],"imageURL":"https://archive.org/services/img/78_blossom-time-waltzes_sigmund-romberg-and-his-orchestra-lehar_gbia0020410","suggestions":["Next"],"album":{"id":"78_blossom-time-waltzes_sigmund-romberg-and-his-orchestra-lehar_gbia0020410","title":"Waltzing with Romberg"},"track":2,"year":null},{"filename":"01 - The Merry Widow Waltzes - Sigmund Romberg and his Orchestra.mp3","title":"The Merry Widow Waltzes","audioURL":"https://archive.org/download/78_blossom-time-waltzes_sigmund-romberg-and-his-orchestra-lehar_gbia0020410/01%20-%20The%20Merry%20Widow%20Waltzes%20-%20Sigmund%20Romberg%20and%20his%20Orchestra.mp3","collections":["78rpm","78rpm_mcneil","georgeblood","audio_music"],"coverage":"USA","creator":["Sigmund Romberg and his Orchestra","Lehar","Dorothy Donnelly","Schubert","Berte","Sigmund Romberg","Ziehrar","Romberg","Oscar Hammerstein, II","Johann Strauss, Jr.","Harbach","Hammerstein II","Mandel"],"imageURL":"https://archive.org/services/img/78_blossom-time-waltzes_sigmund-romberg-and-his-orchestra-lehar_gbia0020410","suggestions":["Next"],"album":{"id":"78_blossom-time-waltzes_sigmund-romberg-and-his-orchestra-lehar_gbia0020410","title":"Waltzing with Romberg"},"track":1,"year":null}]}},"amzn1.ask.device.AHDIDEBSPA33HUZNNIBVHB6SREO4JSWUYWQFDHQ5OTFMYIG272UYLLQD4AZT3G3JJODENWL7QMM7LJXBGE7U7GTCYBJBMYWPPFNQS6YXBM6GDF7PCE5SKEY6PRAADE57JDU2GNIPOFR6KLH7ORYHQNAX6KXQ":{"fsm":{"state":"search-music"},"dialog":{"lastPhrase":{"speech":"You've selected 78s. What genre of music would you like to listen to? Please select a topic like Jazz, Instrumental or Dance?","suggestions":["Jazz","Instrumental","Dance"],"reprompt":null}},"playlist":{"current":0,"feederName":"albums-async","items":[],"extra":{"cursor":{"current":{"song":0,"album":0},"total":{"songs":0,"albums":0}}}},"query":{"values":{"collectionId":"georgeblood","subject":"droll","order":"random"}}}}}
handlerInput.attributesManager.setPersistentAttributes(persistentAttributes)
```

## Current Behavior
but sometimes (more than half of times) I'm getting error:
```javascript
Caught Error: { AskSdk.DynamoDbPersistenceAdapter Error: Could not save item (amzn1.ask.account......) to table (InternetArchiveSessions): The parameter cannot be converted to a numeric value: NaN
    at Object.createAskSdkError (./functions/node_modules/ask-sdk-dynamodb-persistence-adapter/dist/utils/AskSdkUtils.js:22:17)
    at DynamoDbPersistenceAdapter.<anonymous> (./functions/node_modules/ask-sdk-dynamodb-persistence-adapter/dist/attributes/persistence/DynamoDbPersistenceAdapter.js:173:45)
    at step (./functions/node_modules/ask-sdk-dynamodb-persistence-adapter/dist/attributes/persistence/DynamoDbPersistenceAdapter.js:44:23)
    at Object.throw (./functions/node_modules/ask-sdk-dynamodb-persistence-adapter/dist/attributes/persistence/DynamoDbPersistenceAdapter.js:25:53)
    at rejected (./functions/node_modules/ask-sdk-dynamodb-persistence-adapter/dist/attributes/persistence/DynamoDbPersistenceAdapter.js:17:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) name: 'AskSdk.DynamoDbPersistenceAdapter Error' }
```
I don't see any long on DynamoDB side.
As well DynamoDB `setPersistentAttributes` works find in other cases.

I've logged putParams from here https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/ask-sdk-dynamodb-persistence-adapter/lib/attributes/persistence/DynamoDbPersistenceAdapter.ts#L135:
```javascript javascript
putParams {"Item":{"id":"amzn1.ask.account.....","attributes":{"amzn1.ask.device.....":{"fsm":{"state":"playback"},"dialog":{"lastPhrase":{"speech":"You've selected 78s. What genre of music would you like to listen to? Please select a topic like Jazz, Instrumental or Dance?","suggestions":["Jazz","Instrumental","Dance"],"reprompt":null}},"query":{"values":{"collectionId":"georgeblood","order":"random","subject":"dance"}},"playlist":{"feederName":"albums-async","extra":{"cursor":{"current":{"album":0,"song":0},"total":{"songs":1,"albums":1358}}},"current":0,"items":[{"filename":"02 - Blossom Time Waltzes - Sigmund Romberg and his Orchestra.mp3","title":"Blossom Time Waltzes","audioURL":"https://archive.org/download/78_blossom-time-waltzes_sigmund-romberg-and-his-orchestra-lehar_gbia0020410/02%20-%20Blossom%20Time%20Waltzes%20-%20Sigmund%20Romberg%20and%20his%20Orchestra.mp3","collections":["78rpm","78rpm_mcneil","georgeblood","audio_music"],"coverage":"USA","creator":["Sigmund Romberg and his Orchestra","Lehar","Dorothy Donnelly","Schubert","Berte","Sigmund Romberg","Ziehrar","Romberg","Oscar Hammerstein, II","Johann Strauss, Jr.","Harbach","Hammerstein II","Mandel"],"imageURL":"https://archive.org/services/img/78_blossom-time-waltzes_sigmund-romberg-and-his-orchestra-lehar_gbia0020410","suggestions":["Next"],"album":{"id":"78_blossom-time-waltzes_sigmund-romberg-and-his-orchestra-lehar_gbia0020410","title":"Waltzing with Romberg"},"track":2,"year":null},{"filename":"01 - The Merry Widow Waltzes - Sigmund Romberg and his Orchestra.mp3","title":"The Merry Widow Waltzes","audioURL":"https://archive.org/download/78_blossom-time-waltzes_sigmund-romberg-and-his-orchestra-lehar_gbia0020410/01%20-%20The%20Merry%20Widow%20Waltzes%20-%20Sigmund%20Romberg%20and%20his%20Orchestra.mp3","collections":["78rpm","78rpm_mcneil","georgeblood","audio_music"],"coverage":"USA","creator":["Sigmund Romberg and his Orchestra","Lehar","Dorothy Donnelly","Schubert","Berte","Sigmund Romberg","Ziehrar","Romberg","Oscar Hammerstein, II","Johann Strauss, Jr.","Harbach","Hammerstein II","Mandel"],"imageURL":"https://archive.org/services/img/78_blossom-time-waltzes_sigmund-romberg-and-his-orchestra-lehar_gbia0020410","suggestions":["Next"],"album":{"id":"78_blossom-time-waltzes_sigmund-romberg-and-his-orchestra-lehar_gbia0020410","title":"Waltzing with Romberg"},"track":1,"year":null}]}},"amzn1.ask.device.AHDIDEBSPA33HUZNNIBVHB6SREO4JSWUYWQFDHQ5OTFMYIG272UYLLQD4AZT3G3JJODENWL7QMM7LJXBGE7U7GTCYBJBMYWPPFNQS6YXBM6GDF7PCE5SKEY6PRAADE57JDU2GNIPOFR6KLH7ORYHQNAX6KXQ":{"fsm":{"state":"search-music"},"dialog":{"lastPhrase":{"speech":"You've selected 78s. What genre of music would you like to listen to? Please select a topic like Jazz, Instrumental or Dance?","suggestions":["Jazz","Instrumental","Dance"],"reprompt":null}},"playlist":{"current":0,"feederName":"albums-async","items":[],"extra":{"cursor":{"current":{"song":0,"album":0},"total":{"songs":0,"albums":0}}}},"query":{"values":{"collectionId":"georgeblood","subject":"droll","order":"random"}}}}},"TableName":"InternetArchiveSessions"}
```

Actually error:
> The parameter cannot be converted to a numeric value: NaN

could be more informative. Which parameter? Why it is converted to numberic value?

## Your Environment
* alexa-sdk@1.0.25
* ask-sdk@2.0.1

## Node.js and NPM Info
* Node.js version used for development: v9.3.0
* NPM version used for development: 5.5.1

**Comment by tianrenz** [comment]
Hi @hyzhak , 

I used your attributes but could not replicate the error. Could you provide more information on how you configure the dynamoDB persistence adapter and maybe if you set up the dynamo table differently?

Regards

**Comment by tianrenz** [comment]
And also, it says you are using both v1 (alexa-sdk )and v2 sdk (ask-sdk), which dynamodbClient did you use?

**Comment by hyzhak** [comment]
Hi @tianrenz,

I'm using v2 sdk (ask-sdk@2.0.1) and ask-sdk-dynamodb-persistence-adapter@2.0.1.
I could put manually this item right to dynamoDB. But when I use `handlerInput.attributesManager.savePersistentAttributes()` I got that strange error.

Thanks

**Comment by tianrenz** [comment]
@hyzhak , could you attach the skillBuilder configuration here. Did you use any customized DynamoDB client for the persistence adapter?

Regards

**Comment by hyzhak** [comment]
@tianrenz 
> could you attach the skillBuilder configuration here

it is quite a big (32k lines), I will think where could I upload and share here.

> Did you use any customized DynamoDB client for the persistence adapter?

no, I'm using original `ask-sdk-dynamodb-persistence-adapter@2.0.1.`.

**Comment by tianrenz** [comment]
@hyzhak , 

just to check, did you used any options other than `.withTableName()` ?

**Comment by hyzhak** [comment]
@tianrenz 
my code to create adapter:


```javascript
  let dynamoDbPersistenceAdapter = new DynamoDbPersistenceAdapter({
    createTable: true,
    tableName: process.env.DYNAMO_DB_SESSION_TABLE || 'InternetArchiveSessions',
  });
```

**Comment by tianrenz** [comment]
I'm using the code below to test. I'm using the attributes you provided above and didn't receive any errors. The dynamoDB tabled is auto created with SDK provided parameter. 

``javascript
const Alexa = require('ask-sdk');

const handler = {
	canHandle(handlerInput) {
		return true;
	},
	async handle(handlerInput) {
		await handlerInput.attributesManager.getPersistentAttributes();
		handlerInput.attributesManager.setPersistentAttributes(attributes);
 		await handlerInput.attributesManager.savePersistentAttributes();

		return handlerInput.responseBuilder.speak('Hello').getResponse();
	}
};
exports.handler = Alexa.SkillBuilders
  .standard()
  .addRequestHandlers(handler)
  .withTableName('MyTest')
  .withAutoCreateTable(true)
  .lambda();

``

**Comment by tianrenz** [comment]
A couple suggestion to try and fix the error: 

- update SDK to the latest version (2.0.3 at this date)
- if using the `ask-sdk` package, there's no need to instantiate the `DynamoDbPersistenceAdapter` yourself, you can use the helper function (i.e.: `withTableName()` and `withAutoCreateTable`) in the `StandardSkillBuilder` to config the adapter instance. 
- Try remove the table (if applicable) and have SDK recreate the table

**Comment by tianrenz** [comment]
![screen shot 2018-05-03 at 3 52 18 pm](https://user-images.githubusercontent.com/26489817/39606379-fbfbe80c-4ee9-11e8-9971-cc8ffc5bb34a.png)
Attached are a screenshot of the table item put using the attributes above

**Comment by hyzhak** [comment]
@tianrenz sorry! It seems I have provided incorrect data, because I was used `util.inspect` to log object. But actual object has `NaN`. 
Thus test case much simpler:

```javascript
handlerInput.attributesManager.setPersistentAttributes({
  value: NaN,
});
return handlerInput.attributesManager.savePersistentAttributes();
```
