### ISSUE TITLE
ReminderManagerServiceClient.deleteReminders() is not a function

### ISSUE THREAD

**Issue by TommyBs** [alexa/alexa-skills-kit-sdk-for-nodejs#548]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
Calling

```
const ReminderManagementServiceClient = serviceClientFactory.getReminderManagementServiceClient();
        
       await ReminderManagementServiceClient.deleteReminders();
```

should delete all reminders. But it actually throws an error that deleteReminders() is not a function yet it is listed in the docs.

It should delete all reminders.

## Current Behavior

An error is thrown saying deleteReminders is not a function.

Error handled: ReminderManagementServiceClient.deleteReminders is not a function TypeError: ReminderManagementServiceClient.deleteReminders is not a function
at Object.handle (/var/task/index.js:225:63)
at GenericHandlerAdapter.<anonymous> (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/handler/GenericHandlerAdapter.js:63:47)
at step (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/handler/GenericHandlerAdapter.js:44:23)
at Object.next (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/handler/GenericHandlerAdapter.js:25:53)
at /var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/handler/GenericHandlerAdapter.js:19:71
at new Promise (<anonymous>)
at __awaiter (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/handler/GenericHandlerAdapter.js:15:12)
at GenericHandlerAdapter.execute (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/handler/GenericHandlerAdapter.js:61:16)
at GenericRequestDispatcher.<anonymous> (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/GenericRequestDispatcher.js:173:58)
at step (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/GenericRequestDispatcher.js:44:23)

## Possible Solution

Either delete all the reminders or update the docs to highlight this isn't a function

## Steps to Reproduce (for bugs)

Create some reminders with a skill, then try to delete them all with the service client.
e.g.

## Context

Docs -> https://ask-sdk-for-nodejs.readthedocs.io/en/latest/Calling-Alexa-Service-APIs.html?highlight=permissions#remindermanagementserviceclient
## Your Environment

* ASK SDK for Node.js used: x.x.x
"ask-sdk-core": "^2.0.7",
    "ask-sdk-model": "^1.4.1",
    "aws-sdk": "^2.326.0",
* Operating System and version:
Using Alexa Hosted Skills
## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by nikhilym** [comment]
Hey @TommyBs , thanks for getting this to our attention. This is a documentation issue in our SDK docs. You can check on the [Reminder Management API Reference developer doc](https://developer.amazon.com/docs/smapi/alexa-reminders-api-reference.html) that there is no such API `delete Reminders` available for use. We will update our docs to get this removed.
